trigger:
- master

pool:
  vmImage: windows-latest

variables:
  - name: Release
    value: 1
  - name: VersionPrefix
    value: 1.1.0
  - name: VersionSuffix
    value: $[counter(variables['VersionPrefix'], 0)]
  - name: NUGET_PACKAGES
    value: $(Pipeline.Workspace)/.nuget/packages

steps:
- checkout: self
  persistCredentials: true

- task: UseDotNet@2
      inputs:
        useGlobalJson: true

- task: NuGetAuthenticate@0

- task: Cache@2
  inputs:
    key: 'nuget | "$(Agent.OS)"'
    path: $(NUGET_PACKAGES)

- bash: export Version="$(VersionPrefix).$(VersionSuffix)" && ./build.sh
  env:
    CoverletExclude: '[*.Tests]*,[*.SeleniumTests]*,[DataDx.Testing*]*'
    
- task: PublishTestResults@2 
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx'
    searchFolder: $(Common.TestResultsDirectory)

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Common.TestResultsDirectory)/*.cobertura.xml'

- bash: git tag $(Build.SourceBranchName)-$(Build.BuildNumber) && git push origin $(Build.SourceBranchName)-$(Build.BuildNumber)
  workingDirectory: $(Build.SourcesDirectory)    

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.BinariesDirectory)/**/*.nupkg'
    publishVstsFeed: 'DataDx/DataDxNuget'
